[package]
name = "kitcar-welcome"
version = "0.1.0-unreleased"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
insim = { path = "../../insim" }
kitcar = { path = "../../kitcar" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
