[package]
name = "insim_derive"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[dependencies]
quote = { version = "1.0" }
proc-macro2 = { version = "1.0"}
proc-macro-error = "1.0.4"
darling = "0.20.3"

[lib]
proc-macro = true
bench = false
doctest = false
