[package]
name = "kitcar"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
async-trait = "0.1.89"
fixedbitset = { workspace = true }
insim = { path = "../insim", version = "4.0.0", features = ["tokio"] }
taffy = "0.9.1"
tokio = { workspace = true, features = ["rt"] }
tokio-util = "0.7.16"
tracing = { workspace = true }

[lints]
workspace = true
