[package]
name = "twenty_second_league"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
anyhow = "*"
humantime-serde = "1.1.1"
if_chain = { workspace = true }
insim = { path = "../../insim", features = ["serde", "blocking"] }
kitcar = { path = "../../kitcar" }
serde = { workspace = true, features = ["derive"] }
serde_norway = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "signal"]}
tokio-util = { workspace = true }
tracing = {workspace = true}
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[lints]
workspace = true
