iname: "CadenceCup"
addr: "188.122.74.156:53321"
admin: "rFcGByyvRevV"
warmup_duration: 5mins

combos:
  - track: FE1X
    layout: "20s_cup"
    target_time: 20s
    restart_after: 10s
    rounds: 5
    allowed_vehicles: []
