iname: "insim.rs/20sl"
addr: "172.24.64.1:29999"
admin: "123!"
warmup_duration: 5mins
rounds: 5

combos:
  - name: "FE1X_20s_cup"
    track: "FE1X"
    layout: "20s_cup"
    laps: 1
    target_time: 20s
    restart_after: 10s
    vehicles:
      - XRT
      - XRG
