addr: "188.122.74.156:53321"
admin: "rFcGByyvRevV"
lobby_duration: 2mins
victory_duration: 5mins
scores_by_position:
  - 10
  - 9
  - 8
  - 7
  - 6
  - 5
  - 4
  - 3
  - 2
  - 1

combos:
  - track: FE1X
    layout: "20s_cup"
    target_time: 20s
    restart_after: 10s
    rounds: 5
    allowed_vehicles: []
