[package]
name = "prefabs-egui"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
eframe = "0.33.3"
egui_plot = "0.34.1"
image = { version = "0.24", features = ["png"] }
insim_core = { path = "../../insim_core" }

[lints]
workspace = true
