[package]
name = "marquee"
version = "0.1.0-unreleased"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = "1.0.86"
clap = { workspace = true, features = ["derive"] }
insim = { path = "../../insim", features = ["tokio", "glam"] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
glam = { workspace = true }
