[package]
name = "clockwork-carnage"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
if_chain = { workspace = true }

insim = { path = "../../insim", features = ["serde", "blocking"] }
kitcar = { path = "../../kitcar" }
taffy = "0.9.2"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "signal", "time", "sync"]}
tracing = {workspace = true}
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[lints]
workspace = true
