[package]
name = "clockwork-carnage"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true

[lib]
name = "clockwork_carnage"
path = "src/lib.rs"

[[bin]]
name = "event"
path = "src/bin/event.rs"

[[bin]]
name = "challenge"
path = "src/bin/challenge.rs"

[dependencies]
anyhow = "1.0.86"
clap = { workspace = true, features = ["derive"] }
insim = { path = "../../insim", features = ["serde", "blocking"] }
kitcar = { path = "../../kitcar" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros", "signal", "time", "sync"]}
tracing = {workspace = true}
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[lints]
workspace = true
