[package]
name = "prefabs"
version = "0.1.0-unreleased"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
clap = { workspace = true, features = ["derive"] }
insim = { path = "../../insim", default-features = false, features = ["tokio", "serde"] }
kitcar = { path = "../../kitcar" }
serde = { workspace = true, features = ["derive"] }
serde_yaml = "0.9"
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
