[package]
name = "prefabs"
version = "0.1.0-unreleased"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = "1.0.101"
clap = { workspace = true, features = ["derive"] }
glam = { workspace = true }
insim = { path = "../../insim", default-features = false, features = ["tokio", "serde", "glam"] }
kitcar = { path = "../../kitcar" }
noise = "0.9.0"
rand = { version = "0.9", features = ["thread_rng"] }
rand_distr = "0.5.1"
serde = { workspace = true, features = ["derive"] }
serde_norway = "0.9.42"
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
