[package]
name = "simple-blocking"
version = "0.1.0-unreleased"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
clap = { workspace = true, features = ["derive"] }
insim = { path = "../../insim", default-features = false, features = ["blocking"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
